CREATE DATABASE IF NOT EXISTS repoprojects_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE repoprojects_db;

DROP TABLE IF EXISTS proyectos;
DROP TABLE IF EXISTS usuarios;

CREATE TABLE usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  hash_password VARCHAR(255) NOT NULL,
  rol ENUM('ALUMNO','DOCENTE','ADMIN') NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE proyectos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  titulo VARCHAR(200) NOT NULL,
  descripcion TEXT NOT NULL,
  ciclo ENUM('DAM','ASIR') NOT NULL,
  curso_academico VARCHAR(9) NOT NULL,
  tecnologias VARCHAR(255) NOT NULL,
  repositorio_url VARCHAR(500) NOT NULL,
  demo_url VARCHAR(500) NULL,
  estado ENUM('BORRADOR','PENDIENTE','PUBLICADO','RECHAZADO') NOT NULL DEFAULT 'BORRADOR',
  usuario_id INT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_proyectos_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);
